require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'feature_setting.gemspec'
RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 10
RSpec/MessageSpies:
  EnforcedStyle: receive
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 105
Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'lib/generators/**/**'
